In [40]:
import pandas as pd

In [41]:
index = pd.to_datetime([1349720105.21, 1349720105.63, 1349720106.532, 1349720106.92312, 1349720107.642], unit='s')
series = pd.Series([1, 2, 3, 4, 5], index=index)
series

2012-10-08 18:15:05.210000    1
2012-10-08 18:15:05.630000    2
2012-10-08 18:15:06.532000    3
2012-10-08 18:15:06.923120    4
2012-10-08 18:15:07.642000    5
dtype: int64

In [42]:
resampled = series.resample('100L').ffill().bfill()
resampled

2012-10-08 18:15:05.200    1.0
2012-10-08 18:15:05.300    1.0
2012-10-08 18:15:05.400    1.0
2012-10-08 18:15:05.500    1.0
2012-10-08 18:15:05.600    1.0
2012-10-08 18:15:05.700    2.0
2012-10-08 18:15:05.800    2.0
2012-10-08 18:15:05.900    2.0
2012-10-08 18:15:06.000    2.0
2012-10-08 18:15:06.100    2.0
2012-10-08 18:15:06.200    2.0
2012-10-08 18:15:06.300    2.0
2012-10-08 18:15:06.400    2.0
2012-10-08 18:15:06.500    2.0
2012-10-08 18:15:06.600    3.0
2012-10-08 18:15:06.700    3.0
2012-10-08 18:15:06.800    3.0
2012-10-08 18:15:06.900    3.0
2012-10-08 18:15:07.000    4.0
2012-10-08 18:15:07.100    4.0
2012-10-08 18:15:07.200    4.0
2012-10-08 18:15:07.300    4.0
2012-10-08 18:15:07.400    4.0
2012-10-08 18:15:07.500    4.0
2012-10-08 18:15:07.600    4.0
Freq: 100L, dtype: float64

In [43]:
resampled['2012-10-08 18:15:05':'2012-10-08 18:15:06']

2012-10-08 18:15:05.200    1.0
2012-10-08 18:15:05.300    1.0
2012-10-08 18:15:05.400    1.0
2012-10-08 18:15:05.500    1.0
2012-10-08 18:15:05.600    1.0
2012-10-08 18:15:05.700    2.0
2012-10-08 18:15:05.800    2.0
2012-10-08 18:15:05.900    2.0
2012-10-08 18:15:06.000    2.0
2012-10-08 18:15:06.100    2.0
2012-10-08 18:15:06.200    2.0
2012-10-08 18:15:06.300    2.0
2012-10-08 18:15:06.400    2.0
2012-10-08 18:15:06.500    2.0
2012-10-08 18:15:06.600    3.0
2012-10-08 18:15:06.700    3.0
2012-10-08 18:15:06.800    3.0
2012-10-08 18:15:06.900    3.0
Freq: 100L, dtype: float64

In [44]:
resampled.to_csv()

'2012-10-08 18:15:05.200,1.0\n2012-10-08 18:15:05.300,1.0\n2012-10-08 18:15:05.400,1.0\n2012-10-08 18:15:05.500,1.0\n2012-10-08 18:15:05.600,1.0\n2012-10-08 18:15:05.700,2.0\n2012-10-08 18:15:05.800,2.0\n2012-10-08 18:15:05.900,2.0\n2012-10-08 18:15:06.000,2.0\n2012-10-08 18:15:06.100,2.0\n2012-10-08 18:15:06.200,2.0\n2012-10-08 18:15:06.300,2.0\n2012-10-08 18:15:06.400,2.0\n2012-10-08 18:15:06.500,2.0\n2012-10-08 18:15:06.600,3.0\n2012-10-08 18:15:06.700,3.0\n2012-10-08 18:15:06.800,3.0\n2012-10-08 18:15:06.900,3.0\n2012-10-08 18:15:07.000,4.0\n2012-10-08 18:15:07.100,4.0\n2012-10-08 18:15:07.200,4.0\n2012-10-08 18:15:07.300,4.0\n2012-10-08 18:15:07.400,4.0\n2012-10-08 18:15:07.500,4.0\n2012-10-08 18:15:07.600,4.0\n'

In [50]:
data_frame = pd.DataFrame(data={'A': [1, 2, 3, 4, 5], 'B': [5, 4, 3, 2, 1]}, index=index)

data_frame = data_frame.resample('100L').ffill().bfill()

In [60]:
data_frame.to_csv('data.csv')

In [61]:
data_frame = pd.DataFrame.from_csv('data.csv')

In [62]:
data_frame

                           A    B
2012-10-08 18:15:05.200  1.0  5.0
2012-10-08 18:15:05.300  1.0  5.0
2012-10-08 18:15:05.400  1.0  5.0
2012-10-08 18:15:05.500  1.0  5.0
2012-10-08 18:15:05.600  1.0  5.0
2012-10-08 18:15:05.700  2.0  4.0
2012-10-08 18:15:05.800  2.0  4.0
2012-10-08 18:15:05.900  2.0  4.0
2012-10-08 18:15:06.000  2.0  4.0
2012-10-08 18:15:06.100  2.0  4.0
2012-10-08 18:15:06.200  2.0  4.0
2012-10-08 18:15:06.300  2.0  4.0
2012-10-08 18:15:06.400  2.0  4.0
2012-10-08 18:15:06.500  2.0  4.0
2012-10-08 18:15:06.600  3.0  3.0
2012-10-08 18:15:06.700  3.0  3.0
2012-10-08 18:15:06.800  3.0  3.0
2012-10-08 18:15:06.900  3.0  3.0
2012-10-08 18:15:07.000  4.0  2.0
2012-10-08 18:15:07.100  4.0  2.0
2012-10-08 18:15:07.200  4.0  2.0
2012-10-08 18:15:07.300  4.0  2.0
2012-10-08 18:15:07.400  4.0  2.0
2012-10-08 18:15:07.500  4.0  2.0
2012-10-08 18:15:07.600  4.0  2.0